# Generated by Django 3.1.2 on 2020-10-22 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('a_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('profile_image', models.ImageField(upload_to='')),
                ('favorites', models.TextField()),
            ],
        ),
    ]
