# Generated by Django 3.1.2 on 2020-10-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.TextField(default=models.TextField()),
        ),
        migrations.AlterField(
            model_name='account',
            name='favorites',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
