# Generated by Django 3.1.2 on 2020-10-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_auto_20201028_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_games',
            field=models.TextField(blank=True),
        ),
    ]
