# Generated by Django 3.1.2 on 2020-10-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0004_profile_favorite_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
