# Generated by Django 3.1.2 on 2020-10-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0005_auto_20201028_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_streamers',
            field=models.TextField(blank=True),
        ),
    ]
