# Generated by Django 3.1.2 on 2020-11-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0006_auto_20201029_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_games',
            field=models.TextField(blank=True, help_text='Add games by seperating with a "|" character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_streamers',
            field=models.TextField(blank=True, help_text='Add streamers by seperating with a "|" character'),
        ),
    ]
